Repository QualitySolution/QSProjects, pull requests merged in 2019-11, with the labels that each got.

#22 Переработана логика отображения состояния загрузки через свойство LoadInProgress
  QS.LibsTest/Project.Journal/ThreadDataLoaderTest.cs
  QS.Project/Project.Journal/DataLoader/ThreadDataLoader.cs
Labels: Refactoring

#18 Резольвер ITDIWidgetResolver используем через DI
  QS.Project.Gtk/Tdi.Gtk/TDIMain.cs
  QS.Project.Gtk/Tdi.Gtk/TabVBox.cs
  QS.Project.Gtk/Tdi.Gtk/TdiNotebook.cs
  QS.Project.Gtk/Tdi.Gtk/TdiSliderTab.cs
Labels: Refactoring

#32 Просто лишняя строчка.
  QS.Project/Project.Journal/JournalViewModelBase.cs
Labels: Cleanup

#29 Удалил неиспользуемый уже токен, оставленный здесь по ошибке.
  QS.Project.Gtk/Project.Search.GtkUI/SearchView.cs
Labels: Refactoring

#30 Исправлен видимо когда-то работающей запуск поиска по клавише "Enter".
  QS.Project.Gtk/Project.Search.GtkUI/SearchView.cs
  QS.Project.Gtk/gtk-gui/QS.Project.Search.GtkUI.SearchView.cs
  QS.Project.Gtk/gtk-gui/gui.stetic
Labels: bug

#38 Добавлен упрощенный журнал для одного типа сущности
  QS.LibsTest/Project.Journal/EntityJournalViewModelBaseTest.cs
  QS.LibsTest/QS.LibsTest.csproj
  QS.LibsTest/TestApp/JournalViewModels/FullQuerySetEntityJournalViewModel.cs
  QS.Project.Gtk/Project.Services.GtkUI/GtkDeleteEntityService.cs
  QS.Project.Gtk/QS.Project.Gtk.csproj
  QS.Project/Project.Journal/EntitiesJournalViewModelBase.cs
  QS.Project/Project.Journal/EntityJournalViewModelBase.cs
  QS.Project/Project.Journal/MultipleEntityJournalViewModelBase.cs
  QS.Project/Project.Journal/SimpleEntityJournalViewModelBase.cs
  QS.Project/Project.Journal/SingleEntityJournalViewModelBase.cs
  QS.Project/Project.Services/IDeleteEntityService.cs
  QS.Project/QS.Project.csproj
Labels: enhancement

#44 EntityWidgetViewBase переименован в WidgetViewBase
  QS.Project.Gtk/QS.Project.Gtk.csproj
  QS.Project.Gtk/Views.GtkUI/WidgetViewBase.cs
Labels: Refactoring
